import {getHotKeywordsData,getSearchGoodsData} from "../../api/search";
export default {
    namespaced:true,
    state:{
        //历史搜索关键词
        historyKwords:uni.getStorageSync('historyKwords')?JSON.parse(uni.getStorageSync('historyKwords')):[],
        kwords:"",//搜索的关键词
        hotKeywords:[],//热门搜索关键词
        searchGoods:[]//菜品搜索数据列表
    },
    mutations:{
        //设置历史关键词
        ["SET_HISTORY_KWRODS"](state:any,payload:{kwords:string}){
            if(payload.kwords){
                if(state.historyKwords.length>0){
                    for(let i=0;i<state.historyKwords.length;i++){
                        //如果历史搜索关键词有相同的关键词
                        if(state.historyKwords[i]==payload.kwords){
                            state.historyKwords.splice(i--,1);//删除相同的关键词
                            break;
                        }
                    }
                }
                //从数组开头添加搜索关键词
                state.historyKwords.unshift(payload.kwords);
                //将关键词保存的缓存中，实现持久保存
                uni.setStorageSync("historyKwords",JSON.stringify(state.historyKwords));
            }
        },
        //设置关键词
        ["SET_KWORDS"](state:any,payload:{kwords:string}){
            state.kwords=payload.kwords;
        },
        //清除历史记录
        ["CLEAR_KWORDS"](state:any,payload:any){
            state.historyKwords=[];//将历史关键词设置为空
            uni.removeStorageSync("historyKwords");//清除历史
        },
        //设置热门搜索关键词
        ["SET_HOTKEYWORDS"](state:any,payload:{hotKeywords:any []}){
            state.hotKeywords=payload.hotKeywords;
        },
        //设置菜品搜索数据
        ["SET_SEARCH_GOODS"](state:any,payload:{searchGoods:any []}){
            state.searchGoods=payload.searchGoods;
        },
        //设置菜品搜索分页数据
        ["SET_SEARCH_GOODS_PAGE"](state:any,payload:any){
            state.searchGoods.push(...payload.searchGoods);
        }
    },
    actions:{
        //显示热门搜索关键词
        getHotKeywords(conText:any,payload:{}){
            getHotKeywordsData(payload).then((res:any)=>{
                if(res.code==200){
                    conText.commit("SET_HOTKEYWORDS",{hotKeywords:res.data});
                }else{
                    conText.commit("SET_HOTKEYWORDS",{hotKeywords:[]});
                }
            })
        },
        //搜索菜品
        getSearchGoods(conText:any,payload:{page:number,kwords:string,lng:number,lat:number,success?:Function}){
            getSearchGoodsData(payload).then((res:any)=>{
                if(res.code==200){
                    conText.commit("SET_SEARCH_GOODS",{searchGoods:res.data});
                    if(payload.success){
                        payload.success(res.pageinfo.pagenum);
                    }
                }else{
                    conText.commit("SET_SEARCH_GOODS",{searchGoods:[]});
                }
            })
        },
        //搜索菜品分页数据
        getSearchGoodsPage(conText:any,payload:{page:number,kwords:string,lng:number,lat:number,success?:Function}){
            getSearchGoodsData(payload).then((res:any)=>{
                if(res.code==200){
                    conText.commit("SET_SEARCH_GOODS_PAGE",{searchGoods:res.data});
                }
            })
        },
    }
}